### ISSUE TITLE
Possible Course Info Errata

### ISSUE THREAD

**Issue by MarkMoretto** [tirthajyoti/ISYE6740#1]
Hi,

On the actual course website for ISYE6740, it looks like the word `Leaning` is used versus `Learning`.

https://pe.gatech.edu/courses/isye-6740-computational-data-analysis-leaning-mining-and-computation-noncredit

Just a heads up!

**Comment by tirthajyoti** [comment]
It seems like a typo. I am not associated with the GaTech staff, so I cannot do much about it. You can bring it to their notice. Closing this issue now.
